blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Blog Admin"
admin.site.site_title = "Blog Admin Portal"
admin.site.index_title = "Welcome to Blog Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# from posts.views import PostCreateView


urlpatterns = [
    path('', views.post_view, name='post_view'),  
    path('<str:username>/', views.post_view, name='post_view_by_user'),
    path('create/', views.post_create, name='post_create'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:pk>/change_category/', views.change_category, name='change_category'),

    
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    post_image = models.ImageField(upload_to='post_pics/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.title
    
    @property
    def total_likes(self):
        return self.likes.count()
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.title}'
    

    
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} likes {self.post.title}'
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CustomPermission(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class CustomRole(models.Model):
    name = models.CharField(max_length=50, unique=True)
    permissions = models.ManyToManyField(CustomPermission, related_name='roles', blank=True)
    users = models.ManyToManyField(User, related_name='custom_roles', blank=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    role = models.ForeignKey(CustomRole, on_delete=models.CASCADE, blank=True, null=True)
    status = models.BooleanField(default=True)
    email = models.EmailField(max_length=254, blank=True, null=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, CustomRole, CustomPermission


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Enter a valid email address.')
    profile_picture = forms.ImageField(required=False, help_text='Upload a profile picture', widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'profile_picture')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile_picture = self.cleaned_data.get('profile_picture')
            if profile_picture:
                profile = Profile.objects.create(user=user, profile_picture=profile_picture)
                profile.save()
        return user


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    facebook = forms.URLField(required=False)
    twitter = forms.URLField(required=False)
    profile_picture = forms.ImageField(widget=forms.FileInput, required=False)
    
    class Meta:
        model = Profile
        fields = ['bio', 'profile_picture', 'facebook', 'twitter']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['email'].initial = self.instance.user.email

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.user.email = self.cleaned_data['email']
        if commit:
            profile.user.save()
            profile.save()
        return profile


class CustomRoleForm(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=CustomPermission.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = CustomRole
        fields = ['name', 'permissions']


class UserEditForm(forms.ModelForm):
    role = forms.ModelChoiceField(queryset=CustomRole.objects.all(), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'role']

    def clean_role(self):
        role = self.cleaned_data.get('role')
        if role and not CustomRole.objects.filter(id=role.id).exists():
            raise forms.ValidationError("Invalid role selected.")
        return role
    

templates/frontend_templates/all_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Recent Posts{% endblock title %}

{% block body %}
<main>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <h2>Recent Posts</h2>
            {% if posts %}
                {% for post in posts %}
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-md-4">
                                {% if post.post_image %}
                                    <img src="{{ post.post_image.url }}" class="img-fluid rounded-start" alt="Post Image">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <strong class="d-inline-block mb-2 text-primary-emphasis">{{ post.category.name }}</strong>
                                    <h5 class="card-title">{{ post.title }}</h5>
                                    <p class="card-text">{{ post.content|truncatewords:40 }}</p>
                                    <p class="card-text"><small class="text-muted">Author: <a href="{% url 'profile_view' username=post.author.username %}">{{ post.author.username }}</a></small></p>
                                    <p class="card-text"><small class="text-muted">Published on: {{ post.date_published }}</small></p>
                                    <a href="{% url 'post_detail' post.pk %}" class="btn btn-sm btn-outline-secondary">Continue Reading</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-center">No posts available.</p>
            {% endif %}
            
            <div class="text-center">
                <a href="{% url 'post_create' %}" class="btn btn-sm btn-outline-secondary">Create New Post</a>
            </div>
        </div>
    </div>
</main>
{% endblock body %}

templates/frontend_templates/category_posts.html
{% extends 'base.html' %}

{% block title %}{{ category }} {% endblock title %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            {% for post in posts %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            {% if post.post_image %}
                                <img src="{{ post.post_image.url }}" class="img-fluid rounded-start" alt="Post Image">
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content | truncatechars:200 }}</p>
                                <p class="card-text"><small class="text-muted">Author: <a href="{% url 'profile_view' username=post.author.username %}">{{ post.author.username }}</a></small></p>
                                <p class="card-text"><small class="text-muted">Published on: {{ post.date_published }}</small></p>
                                <a href="{% url 'post_detail' post.pk %}" class="btn btn-sm btn-outline-secondary">Continue Reading</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No posts available in this category.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

templates/frontend_templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile | Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog.css' %}">
</head>
<body>
    <div class="container">
        <header class="border-bottom lh-1 py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'home' %}">My Blog</a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'home' %}" style="margin-right: 10px;">Log out</a>
                </div>
            </div>
        </header>
        
        <main>
            <div class="row justify-content-center mt-5">
                <div class="col-md-8">
                    <div class="profile-details">
                        <h2><strong>Edit Profile</strong></h2>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_username" class="form-label"><strong>Username</strong></label>
                                <input type="text" id="id_username" name="username" class="form-control" value="{{ user.username }}" required autofocus>
                                {% if form.username.errors %}
                                    <div class="text-danger">
                                        {{ form.username.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_email" class="form-label"><strong>Email</strong></label>
                                <input type="email" id="id_email" name="email" class="form-control" value="{{ user.email }}" required>
                                {% if form.email.errors %}
                                    <div class="text-danger">
                                        {{ form.email.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_bio" class="form-label"><strong>{{form.bio.label}}</strong></label>
                                <input type="text" id="id_bio" name="bio" class="form-control" value="{{ profile.bio }}">
                                {% if form.bio.errors %}
                                    <div class="text-danger">
                                        {{ form.bio.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_profile_picture" class="form-label"><strong>Profile Picture</strong></label>
                                {% if profile.profile_picture %}
                                    <img src="{{ profile.profile_picture.url }}" alt="Current Profile Picture" style="max-width: 200px; max-height: 200px; margin-bottom: 10px;">
                                {% endif %}
                            </div>
                            <div>
                                <label for="id_profile_picture" class="form-label"><strong>Change Profile Picture</strong></label>
                                <input type="file" id="id_profile_picture" name="profile_picture" class="form-control" accept="image/*">
                                {% if form.profile_picture.errors %}
                                    <div class="text-danger">
                                        {{ form.profile_picture.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_facebook" class="form-label"><strong>Facebook (optional)</strong></label>
                                <input type="url" id="id_facebook" name="facebook" class="form-control" value="{{ form.facebook.value|default_if_none:'' }}">
                                {% if form.facebook.errors %}
                                    <div class="text-danger">
                                        {{ form.facebook.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_twitter" class="form-label"><strong>Twitter (optional)</strong></label>
                                <input type="url" id="id_twitter" name="twitter" class="form-control" value="{{ form.twitter.value|default_if_none:'' }}">
                                {% if form.twitter.errors %}
                                    <div class="text-danger">
                                        {{ form.twitter.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </form>
                    </div>
                </div>        
            </div>
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/frontend_templates/profile_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ profile.user.username }}'s Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog.css' %}">
    <style>
        .profile-circle {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            overflow: hidden;
        }
        .profile-circle img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .btn-group .btn {
            white-space: nowrap; /* Prevent button text from wrapping */
        }
    </style>
</head>
<body>
    <div class="container">
        <header class="border-bottom lh-1 py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'home' %}">My Blog</a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <form class="d-flex me-2" action="{% url 'search' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                    </form>
                    {% if request.user.is_authenticated %}
                    <div class="btn-group">
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'post_create' %}">New Post</a>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}" style="margin-right: 10px;">Log out</a>
                    </div>
                    <a href="{% url 'profile' %}" class="profile-circle me-2">
                      {% if request.user.profile.profile_picture %}
                      <img src="{{ request.user.profile.profile_picture.url }}" alt="Profile Picture">
                      {% else %}
                      <img src="{% static 'img/default_profile.jpg' %}" alt="Default Profile Picture">
                      {% endif %}
                  </a>
                    {% else %}
                    <a class="btn btn-sm btn-outline-secondary me-2" href="{% url 'login' %}">Log in</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'signup' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </header>

        <main>
            <div class="container mt-4">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h2 class="card-title">{{ profile.user.username }}'s Profile</h2>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4 text-center">
                                        {% if profile.profile_picture %}
                                            <img src="{{ profile.profile_picture.url }}" class="img-fluid rounded-circle" alt="Profile Picture">
                                        {% else %}
                                            <img src="{% static 'default_profile.jpg' %}" class="img-fluid rounded-circle" alt="Profile Picture">
                                        {% endif %}
                                    </div>
                                    <div class="col-md-8">
                                        <p><strong>Bio:</strong> {{ profile.bio }}</p>
                                        <p><strong>Email:</strong> {{ profile.user.email }}</p>
                                        <p><strong>Joined:</strong> {{ profile.user.date_joined|date:"F d, Y" }}</p>
                                        <div class="social-icons">
                                            {% if profile.facebook %}
                                            <a href="{{ profile.facebook }}" class="nav-link">
                                                <i class="fab fa-facebook-f"></i>
                                            </a>
                                            {% endif %}
                                            
                                            {% if profile.twitter %}
                                            <a href="{{ profile.twitter }}" class="nav-link">
                                                <i class="fab fa-twitter"></i>
                                            </a>
                                            {% endif %}
                                        </div>
                                        <p><strong>Total Posts:</strong> <a href="{% url 'post_view_by_user' username=profile.user.username %}">{{ profile.user.post_set.count }}</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <!-- Bootstrap and other scripts -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/frontend_templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Signup{% endblock title %}

{% block body %}
{% load widget_tweaks %}

<div class="container">
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                                    
                                    {% if form.errors %}
                                    <div class="alert alert-danger">
                                        {{ form.non_field_errors }}
                                    </div>
                                    {% endif %}
                                    
                                    <form method="post" action="{% url 'signup' %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        
                                        <div class="mb-4">
                                            <label for="id_username" class="form-label">Username</label>
                                            {{ form.username|add_class:"form-control" }}
                                            {% if form.username.errors %}
                                                <div class="text-danger">
                                                    {{ form.username.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="mb-4">
                                            <label for="id_email" class="form-label">Email</label>
                                            {{ form.email|add_class:"form-control" }}
                                            {% if form.email.errors %}
                                                <div class="text-danger">
                                                    {{ form.email.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="mb-4">
                                            <label for="id_password1" class="form-label">Password</label>
                                            {{ form.password1|add_class:"form-control" }}
                                            {% if form.password1.errors %}
                                                <div class="text-danger">
                                                    {{ form.password1.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="mb-4">
                                            <label for="id_password2" class="form-label">Repeat your password</label>
                                            {{ form.password2|add_class:"form-control" }}
                                            {% if form.password2.errors %}
                                                <div class="text-danger">
                                                    {{ form.password2.errors }}
                                                </div>
                                            {% endif %}
                                        </div>

                                        <div class="mb-4">
                                            <label for="id_profile_picture" class="form-label">Profile Picture</label>
                                            {{ form.profile_picture|add_class:"form-control" }}
                                            {% if form.profile_picture.errors %}
                                                <div class="text-danger">
                                                    {{ form.profile_picture.errors }}
                                                </div>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="form-check d-flex justify-content-center mb-5">
                                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                                            <label class="form-check-label" for="form2Example3">
                                                I agree all statements in <a href="#!">Terms of service</a>
                                            </label>
                                        </div>
                                        
                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Register</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock body %}