blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Blog Admin"
admin.site.site_title = "Blog Admin Portal"
admin.site.index_title = "Welcome to Blog Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# from posts.views import PostCreateView


urlpatterns = [
    path('', views.post_view, name='post_view'),  
    path('<str:username>/', views.post_view, name='post_view_by_user'),
    path('create/', views.post_create, name='post_create'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:pk>/change_category/', views.change_category, name='change_category'),

    
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    post_image = models.ImageField(upload_to='post_pics/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.title
    
    @property
    def total_likes(self):
        return self.likes.count()
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.title}'
    

    
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} likes {self.post.title}'
    

posts/forms.py
from django import forms
from .models import Post, Comment, Category

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'content', 'post_image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'post_image': forms.FileInput(attrs={'class': 'form-control', 'accept': 'image/*'}),
        }

    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     if commit:
    #         user.save()
    #         post_image = self.cleaned_data.get('post_image')
    #         if post_image:
    #             post = Post.objects.create(user=user, post_image=post_image)
    #             post.save()
    #     return user

class ChangeCategoryForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 3, 'class': 'form-control', 'placeholder': 'Write your comment here...'})
        }

class LikeForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = []

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Like, Category   
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from .forms import PostForm, CommentForm, ChangeCategoryForm
from django.http import HttpResponse
from users.models import User
from django.views import View
from django.contrib import messages


# Create your views here.


def check_role_permissions(user, required_permissions=None):
    if user.is_superuser:
        return True
    if user.is_authenticated and user.profile.role:
        if required_permissions is None:
            return True  # If no specific permissions are required, allow access
        user_permissions = set(user.profile.role.permissions.values_list('name', flat=True))
        return set(required_permissions).issubset(user_permissions)
    return False

def check_role(user, required_roles=None):
    if user.is_superuser:
        return True  # Superusers can be considered to have all roles

    if user.is_authenticated and user.profile.role:
        if required_roles is None:
            return True  # If no specific roles are required, allow access
        return user.profile.role.name in required_roles

    return False

@login_required
def post_view(request, username=None):
    """this function works as a view function for blog posts
    
    Keyword arguments:
    username -- to show the users posts
    Return: returns django template
    """
    
    if username:
        user = get_object_or_404(User, username=username)
        posts = Post.objects.filter(is_active=True, author=user)
        profile = user.profile
    else:
        user = request.user
        posts = Post.objects.filter(is_active=True, author=request.user)
        profile = user.profile if user.is_authenticated else None
    
    context = {
        'profile': user.profile,
        'posts': posts,
    }
    return render(request, 'post_view.html', context)


@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can create post']))
def post_create(request):
    """sumary_line
    
    Keyword arguments:
    argument -- description
    Return: return_description
    """
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)  
    else:
        form = PostForm()

    categories = Category.objects.all()
    
    context = {
        'form': form,
        'categories': categories,
    }
    return render(request, 'post_create.html', context)


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post_detail', pk=pk)
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'edit_post.html', context)


@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can change category']))
def change_category(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = ChangeCategoryForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category changed successfully.')
            return redirect('post_detail', pk=post.pk)
    else:
        form = ChangeCategoryForm(instance=post)

    context = {
        'post': post,
        'form': form,
    }

    return render(request, 'change_category.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.filter(enabled=True)
    comment_form = CommentForm()
    categories = Category.objects.all()

    liked = False
    if request.user.is_authenticated:
        liked = post.likes.filter(user=request.user).exists()

    if request.user == post.author:
        can_edit = True
    else:
        can_edit = False

    if request.method == 'POST':
        form = ChangeCategoryForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category changed successfully.')
            return redirect('post_detail', pk=post.pk)
    else:
        form = ChangeCategoryForm(instance=post)  # Initial form instantiation

    context = {
        'post': post,
        'categories': categories,
        'comments': comments,
        'liked': liked,
        'comment_form': comment_form,
        'can_edit': can_edit,
        'change_category_form': form, 
    }
    return render(request, 'post_detail.html', context)


@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can add comment']))
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.all()
    categories = Category.objects.all()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        comment_form = CommentForm()

    liked = post.likes.filter(user=request.user).exists()

    context = {
        'post': post,
        'categories': categories,
        'comments': comments,
        'comment_form': comment_form,
        'liked': liked,
    }
    return render(request, 'post_detail.html', context)


@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can delete comment']))
def delete_comment(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    
    if request.user == comment.user:
        comment.delete()
        messages.success(request, 'Comment deleted successfully.')

    return redirect('post_detail', pk=post_pk)



@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can add like']))
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    liked = post.likes.filter(user=request.user).exists()

    if liked:
        post.likes.filter(user=request.user).delete()
    else:
        Like.objects.create(post=post, user=request.user)

    return redirect('post_detail', pk=pk)


@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can edit post']))
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk, author=request.user)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            updated_post = form.save(commit=False)
            if 'post_image' in request.FILES:
                updated_post.post_image = request.FILES['post_image']
            updated_post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'post_edit.html', context)

templates/backend_templates/posts/create_post.html
{% extends "backend_base.html" %}
{% load static %}

{% block title %}Create Post{% endblock title %}

{% block body %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-xl-8 col-lg-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Create Post</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group input-group-outline mb-3">
                            <input type="text" id="id_title" name="title" class="form-control" required placeholder="Title">
                        </div>
                        <div class="mb-3">
                            <label for="id_category" class="form-label">Category</label>
                            <select id="id_category" name="category" class="form-select ps-2" required>
                                <option value="" selected disabled>Select Category</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <textarea class="form-control" id="id_content" name="content" rows="5" required placeholder="Content"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="id_post_image" class="form-label">Post Image</label>
                            <input type="file" id="id_post_image" name="post_image" class="input-group input-group-outline mb-3">
                        </div>
                        <button type="submit" class="btn btn-primary">Create Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/backend_templates/posts/edit_category.html
{% extends "backend_base.html" %}
{% load static %}

{% block title %}Edit Category{% endblock title %}

{% block body %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-xl-4 col-lg-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Edit Category for {{ post.title }}</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="outline mb-3">
                            <label for="id_category" class="form-label">Category</label>
                            <select id="id_category" name="category" class="form-select ps-2" required>
                                <option value="" selected disabled>Select Category</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}" {% if category.id == post.category.id %} selected {% endif %}>{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/backend_templates/posts/posts.html
{% extends "backend_base.html" %}
{% load static %}

{% block title %}Posts{% endblock title %}

{% block body %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <a href="{% url 'create_post' %}" class="btn btn-primary mb-3">Create Post</a>
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">Posts Table</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Post</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Category</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Author</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date Published</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Action</th>
                                    <th class="text-secondary opacity-7"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post in posts %}
                          <tr>
                            <td>
                                <a href="{% url 'post_detail' pk=post.pk %}" class="text-decoration-none text-reset">
                                    <div class="d-flex px-2 py-1">
                                        {% if post.post_image %}
                                            <div>
                                                <img src="{{ post.post_image.url }}" class="avatar avatar-sm me-3 rounded-circle" alt="Post Image" width="50" height="50">
                                            </div>
                                        {% endif %}
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-sm">{{ post.title }}</h6>
                                        </div>
                                    </div>
                                </a>
                            </td>
                              <td class="text-xs font-weight-bold text-center align-middle">
                                    {{ post.category }}
                                </td>
                              <td class="text-center align-middle">
                                <div class="avatar-group mt-2">
                                    <a href="{% url 'profile_view' username=post.author.username %}" class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ post.author.username }}" data-bs-trigger="hover focus">
                                        <img src="{{ post.author.profile.profile_picture.url }}" class="avatar avatar-sm me-3 rounded-circle" alt="Author Profile Picture" width="50" height="50">                                    </a>
                                </div>
                            </td>
                            
                            <td class="align-middle text-center text-sm">
                                {% if post.is_active %}
                                <form id="disableForm{{ post.id }}" action="{% url 'disable_post' post.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="d-none"></button>
                                    <a href="#" class="badge bg-gradient-secondary text-decoration-none" onclick="confirmAction({{ post.id }}, 'disable');">
                                        Disable
                                    </a>
                                </form>
                                {% else %}
                                <form id="enableForm{{ post.id }}" action="{% url 'enable_post' post.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="d-none"></button>
                                    <a href="#" class="badge bg-gradient-success text-decoration-none" onclick="confirmAction({{ post.id }}, 'enable');">
                                        Enable
                                    </a>                        
                                </form>
                                {% endif %}
                              </td>

                              <td class="align-middle text-center text-sm">
                                  <span class="text-xs font-weight-bold">{{ post.date_published|date:"F j, Y" }}</span>
                              </td>
                              <td class="align-middle text-center text-sm">
                                <div class="d-flex justify-content-center">
                                    <a href="{% url 'edit_category' post.id %}" class="text-secondary font-weight-bold text-sm me-2" data-toggle="tooltip" data-original-title="Edit post">
                                        Edit Category
                                    </a>
                                    <form id="deletePostForm{{ post.id }}" action="{% url 'delete_post' post.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="d-none"></button>
                                        <a href="#" class="badge bg-gradient-danger text-decoration-none" onclick="confirmAction({{ post.id }}, 'delete');" data-toggle="tooltip" data-original-title="Delete post">Delete</a>
                                    </form>
                                </div>
                            </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Include SweetAlert2 library -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function confirmAction(postId, action) {
        let title, text, confirmButtonText, formId;
        
        if (action === 'delete') {
            title = "Are you sure you want to delete?";
            text = "You won't be able to revert this!";
            confirmButtonText = "Yes, delete it!";
            formId = 'deletePostForm';
        } else if (action === 'disable') {
            title = "Are you sure you want to disable?";
            text = "This post will no longer be visible to users.";
            confirmButtonText = "Yes, disable it!";
            formId = 'disableForm';
        } else if (action === 'enable') {
            title = "Are you sure you want to enable?";
            text = "This post will become visible to users.";
            confirmButtonText = "Yes, enable it!";
            formId = 'enableForm';
        }
    
        Swal.fire({
            title: title,
            text: text,
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: confirmButtonText
        }).then((result) => {
            if (result.isConfirmed) {
                let successTitle, successText;
                if (action === 'delete') {
                    successTitle = "Deleted";
                    successText = "The post has been deleted successfully.";
                } else if (action === 'disable') {
                    successTitle = "Disabled";
                    successText = "The post has been disabled successfully.";
                } else if (action === 'enable') {
                    successTitle = "Enabled";
                    successText = "The post has been enabled successfully.";
                }
                
                document.getElementById(formId + postId).submit();
                
                Swal.fire({
                    title: successTitle,
                    text: successText,
                    icon: "success",
                    showConfirmButton: false // Hide the "OK" button
                });
            }
        });
    }
</script>





{% endblock body %}