blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Blog Admin"
admin.site.site_title = "Blog Admin Portal"
admin.site.index_title = "Welcome to Blog Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# from posts.views import PostCreateView


urlpatterns = [
    path('', views.post_view, name='post_view'),  
    path('<str:username>/', views.post_view, name='post_view_by_user'),
    path('create/', views.post_create, name='post_create'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('<int:pk>/add_comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:pk>/change_category/', views.change_category, name='change_category'),

    
]

users/urls.py
from django.urls import path
from users import views
from .views import signup_view
from posts import views as post_views


urlpatterns = [
    path('', views.index, name='home'),
    path('world/', views.world, name='world'),
    path('technology/', views.technology, name='technology'),
    path('design/', views.design, name='design'),
    path('culture/', views.culture, name='culture'),
    path('politics/', views.politics, name='politics'),
    path('science/', views.science, name='science'),
    path('health/', views.health, name='health'),
    path('travel/', views.travel, name='travel'),
    path('signup/', signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('backend/', views.backend, name="backend"),
    path('backend_profile/', views.backend_profile, name='backend_profile'),
    path('backend/dashboard/', views.dashboard, name='dashboard'),
    path('backend/users/', views.users, name='users'),
    path('backend/manage/users/add/', views.add_user, name='add_user'),
    path('disable_user/<int:user_id>/', views.disable_user, name='disable_user'),
    path('enable_user/<int:user_id>/', views.enable_user, name='enable_user'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('users/delete/<int:user_id>', views.delete_user, name='delete_user'),
    path('backend/posts/', views.posts, name='posts'),
    path('backend/posts/create/', views.create_post, name='create_post'),
    path('edit_category/<int:post_id>/', views.edit_category, name='edit_category'),
    path('disable_post/<int:post_id>/', views.disable_post, name='disable_post'),
    path('enable_post/<int:post_id>/', views.enable_post, name='enable_post'),
    path('posts/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('backend/comments/', views.comments, name='comments'),
    path('enable_comment/<int:comment_id>/', views.enable_comment, name='enable_comment'),
    path('disable_comment/<int:comment_id>/', views.disable_comment, name='disable_comment'),
    path('comments/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),

    path('profile/', views.profile, name='profile'),
    path('editprofile/', views.edit_profile, name='edit_profile'),

    path('all_posts/', views.all_posts, name='all_posts'),

    path('profile/<str:username>/', views.profile_view, name='profile_view'),

    path('posts/create/', post_views.post_create, name='post_create'),

    path('search/', views.search_view, name='search'),


    path('manage-roles/', views.manage_roles, name='manage_roles'),
    path('add_role/', views.add_role, name='add_role'),
    path('edit_role/<int:role_id>/', views.edit_role, name='edit_role'),

    path('view_permissions/<int:role_id>/', views.view_permissions, name='view_permissions'),


]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CustomPermission(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class CustomRole(models.Model):
    name = models.CharField(max_length=50, unique=True)
    permissions = models.ManyToManyField(CustomPermission, related_name='roles', blank=True)
    users = models.ManyToManyField(User, related_name='custom_roles', blank=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    role = models.ForeignKey(CustomRole, on_delete=models.CASCADE, blank=True, null=True)
    status = models.BooleanField(default=True)
    email = models.EmailField(max_length=254, blank=True, null=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, CustomRole, CustomPermission


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Enter a valid email address.')
    profile_picture = forms.ImageField(required=False, help_text='Upload a profile picture', widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'profile_picture')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile_picture = self.cleaned_data.get('profile_picture')
            if profile_picture:
                profile = Profile.objects.create(user=user, profile_picture=profile_picture)
                profile.save()
        return user


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    facebook = forms.URLField(required=False)
    twitter = forms.URLField(required=False)
    profile_picture = forms.ImageField(widget=forms.FileInput, required=False)
    
    class Meta:
        model = Profile
        fields = ['bio', 'profile_picture', 'facebook', 'twitter']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['email'].initial = self.instance.user.email

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.user.email = self.cleaned_data['email']
        if commit:
            profile.user.save()
            profile.save()
        return profile


class CustomRoleForm(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=CustomPermission.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = CustomRole
        fields = ['name', 'permissions']


class UserEditForm(forms.ModelForm):
    role = forms.ModelChoiceField(queryset=CustomRole.objects.all(), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'role']

    def clean_role(self):
        role = self.cleaned_data.get('role')
        if role and not CustomRole.objects.filter(id=role.id).exists():
            raise forms.ValidationError("Invalid role selected.")
        return role
    

users/views.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.csrf import csrf_protect
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import SignUpForm, ProfileForm, CustomRoleForm
from posts.forms import PostForm, ChangeCategoryForm
from .models import Profile, CustomRole, CustomPermission
from posts.models import Post, Comment, Category
from django.db import IntegrityError
from django.db.models import Q
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.core.exceptions import ValidationError



def index(request):
    recent_posts = Post.objects.order_by('-date_published')[:3] 
    context = {
        'recent_posts': recent_posts,
    }
    return render(request, 'index.html', context)

def world(request):
    posts = Post.objects.filter(category__name='World')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'World'})

def technology(request):
    posts = Post.objects.filter(category__name='Technology')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Technology'})

def design(request):
    posts = Post.objects.filter(category__name='Design')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Design'})

def culture(request):
    posts = Post.objects.filter(category__name='Culture')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Culture'})

def politics(request):
    posts = Post.objects.filter(category__name='Politics')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Politics'})

def science(request):
    posts = Post.objects.filter(category__name='Science')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Science'})

def health(request):
    posts = Post.objects.filter(category__name='Health')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Health'})

def travel(request):
    posts = Post.objects.filter(category__name='Travel')
    return render(request, 'category_posts.html', {'posts': posts, 'category': 'Travel'})

@csrf_protect
def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            subject = 'Welcome to our Blog'
            message = render_to_string('email.html', {'user': user})
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [user.email],
                fail_silently=False,
            )
            login(request, user)
            return redirect('profile')  
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.profile.status:
                    login(request, user)
                    if user.profile.role.name == 'admin':
                        return redirect('backend')
                    else:
                        return redirect('home')
                else:
                    messages.error(request, "Your account is disabled. Please contact the administrator.")
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

@login_required
def backend(request):
    title= 'Backend'
    return render(request, 'backend_base.html', {'title':title})

@login_required
def backend_profile(request):
    title = 'Backend Profile'
    try:
        profile = Profile.objects.get(user=request.user)
        posts = Post.objects.filter(author=request.user)
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)
        posts = []
    
    context = {
        'title': title,
        'profile': profile,
        'user': request.user,
        'posts': posts,
    }
    return render(request, 'backend_profile.html', context)

@login_required
def dashboard(request):
    title = 'Dashboard'
    total_posts = Post.objects.count()
    total_comments = Comment.objects.count()
    total_users = User.objects.count()
    total_disabled_posts = Post.objects.filter(is_active=False).count()
    recent_posts = Post.objects.order_by('-date_published')[:10]
    recent_comments = Comment.objects.order_by('-created_at')[:10]
    context = {
        'title': title,
        'total_posts': total_posts,
        'total_comments': total_comments,
        'total_users': total_users,
        'total_disabled_posts': total_disabled_posts,
        'recent_posts': recent_posts,
        'recent_comments': recent_comments,
    }

    return render(request, 'dashboard.html', context)

@login_required
def users(request):
    title = 'Users'
    profiles = Profile.objects.select_related('user', 'role').all()
    return render(request, 'users.html', {'profiles': profiles, 'title': title})


@login_required
def add_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        role_id = request.POST['role']
        status = 'status' in request.POST
        password = request.POST['password']
        profile_picture = request.FILES.get('profile_picture', None)

        try:
            user = User.objects.create_user(username=username, email=email, password=password)
            
            role = CustomRole.objects.get(id=role_id)
            profile = Profile.objects.create(user=user, role=role, status=status)

            if profile_picture:
                profile.profile_picture = profile_picture
                profile.save()

            return redirect('users')

        except IntegrityError:
            error_message = 'Username already exists.'
            roles = CustomRole.objects.all()  
            return render(request, 'add_user.html', {'error_message': error_message, 'roles': roles})

    else:
        roles = CustomRole.objects.all()
        return render(request, 'add_user.html', {'roles': roles})



@require_POST
@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can manage user']))
def disable_user(request, user_id):
    if request.method == 'POST':
        profile = get_object_or_404(Profile, user_id=user_id)
        profile.status = False
        profile.save()
    return redirect('users')

@require_POST
@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can manage user']))
def enable_user(request, user_id):
    if request.method == 'POST':
        profile = get_object_or_404(Profile, user_id=user_id)
        profile.status = True
        profile.save()
    return redirect('users')

@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can edit user']))
def edit_user(request, user_id):
    profile = Profile.objects.get(user_id=user_id)
    
    if request.method == 'POST':
        try:
            username = request.POST['username']
            email = request.POST['email']
            bio = request.POST['bio']
            role_id = request.POST['role']
            status = request.POST.get('status') == 'on'
            
            profile.user.username = username
            profile.user.email = email
            profile.bio = bio
            profile.role = CustomRole.objects.get(id=role_id)
            profile.status = status
            
            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']
            
            profile.user.save()
            profile.save()
            
            return redirect('users')
        
        except IntegrityError:
            return render(request, 'edit_user.html', {'profile': profile, 'roles': CustomRole.objects.all(), 'error_message': 'Username already exists.'})
        except ValidationError as e:
            return render(request, 'edit_user.html', {'profile': profile, 'roles': CustomRole.objects.all(), 'error_message': str(e)})

    roles = CustomRole.objects.all()
    
    return render(request, 'edit_user.html', {'profile': profile, 'roles': roles})



@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can delete user']))
def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    messages.success(request, 'User deleted successfully.')
    return redirect('users')



@login_required
@user_passes_test(lambda u: check_role_permissions(u, ['Can manage post']))
def posts(request):
    title = 'Posts'
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts, 'title': title})


def disable_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.is_active = False
        post.save()
        messages.success(request, "The post has been disabled successfully.")
    return redirect('posts')

def enable_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.is_active = True
        post.save()

templates/backend_templates/users/add_user.html
{% extends "backend_base.html" %}

{% block title %}Add User{% endblock title %}

{% block body %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-xl-4 col-lg-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Add User</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group input-group-outline mb-3">
                            <input type="text" id="id_username" name="username" class="form-control" required placeholder="Username">
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <input type="email" id="id_email" name="email" class="form-control" required placeholder="Email">
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <input type="password" id="id_password" name="password" class="form-control" required placeholder="Password">
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            <select id="id_role" name="role" class="form-select ps-3" required>
                                <option value="" selected disabled>Select Role</option>
                                {% for role in roles %}
                                    <option value="{{ role.id }}">{{ role.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="id_profile_picture" class="form-label">Profile Picture</label>
                            <input type="file" id="id_profile_picture" name="profile_picture" class="input-group input-group-outline mb-3">
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="id_status" name="status" checked
                                   style="background-color: #e91e63; border-color: #e91e63;"
                                   onchange="this.style.backgroundColor = this.checked ? '#e91e63' : '#adb5bd';">
                            <label class="form-check-label" for="id_status">Enable User</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Add User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/backend_templates/users/edit_user.html
{% extends "backend_base.html" %}

{% block title %}Edit User{% endblock title %}

{% block body %}
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-xl-4 col-lg-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Edit User</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control ps-2" id="id_username" name="username" value="{{ profile.user.username }}" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control ps-2" id="id_email" name="email" value="{{ profile.user.email }}" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_bio" class="form-label">Bio</label>
                            <textarea class="form-control ps-2" id="id_bio" name="bio" rows="3">{{ profile.bio }}</textarea>
                        </div>                        
                        <div class="mb-3">
                            <label for="id_role" class="form-label">Role</label>
                            <select class="form-select ps-2" id="id_role" name="role" required>
                                <option value="" selected disabled>Select Role</option>
                                {% for role in roles %}
                                    <option value="{{ role.id }}" {% if profile.role.id == role.id %}selected{% endif %}>{{ role.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="id_profile_picture" class="form-label">Profile Picture</label>
                            <input type="file" id="id_profile_picture" name="profile_picture" class="input-group input-group-outline mb-3">
                        </div>
                        <div class="form-check form-switch mb-3">
                            <input class="form-check-input" type="checkbox" id="id_status" name="status" {% if profile.status %}checked{% endif %} style="background-color: #e91e63; border-color: #e91e63;" onchange="this.style.backgroundColor = this.checked ? '#e91e63' : '#adb5bd';">
                            <label class="form-check-label" for="id_status">Enable User</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Update User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/backend_templates/users/users.html
{% extends "backend_base.html" %}
{% load static %}

{% block title %}Users{% endblock title %}

{% block body %}


<div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
        <a href="{% url 'add_user' %}" class="btn btn-primary mb-3">Add User</a>
        <div class="card my-4">
          <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
            <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
              <h6 class="text-white text-capitalize ps-3">Users table</h6>
            </div>
          </div>
          <div class="card-body px-0 pb-2">
            <div class="table-responsive p-0">
              <table class="table align-items-center mb-0">
                <thead>
                  <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">User</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Role</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date Joined</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Action</th>
                    <th class="text-secondary opacity-7"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for profile in profiles %}
                  <tr>
                      <td>
                          <div class="d-flex px-2 py-1">
                              <div class="avatar avatar-sm me-3 rounded-circle">
                                  {% if profile.profile_picture %}
                                  <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" width="50" height="40">
                                  {% else %}
                                  <img src="{% static 'img/avatar.png' %}" alt="Default Profile Picture" width="50" height="40">
                                  {% endif %}
                              </div>
                        <div class="d-flex flex-column justify-content-center">
                            <a href="{% url 'profile_view' username=profile.user.username %}" class="text-decoration-none text-reset">
                                <h6 class="mb-0 text-sm">{{ profile.user.username }}</h6>
                              </a>
                              <p class="text-xs text-secondary mb-0">{{ profile.user.email }}</p>
                        </div>
                      </div>
                    </td>
                    <td>{{ profile.role.name|default:"No role assigned" }}</td>
                    <td class="align-middle text-center text-sm">
                      {% if profile.status %}
                      <form id="disableForm{{ profile.user.id }}" action="{% url 'disable_user' profile.user.id %}" method="post" style="display: inline;">
                          {% csrf_token %}
                          <button type="submit" class="d-none"></button>
                          <a href="#" class="badge bg-gradient-secondary text-decoration-none" onclick="event.preventDefault(); confirmAction('{{ profile.user.id }}', 'disable');">
                              Disable
                          </a>
                      </form>
                      {% else %}
                      <form id="enableForm{{ profile.user.id }}" action="{% url 'enable_user' profile.user.id %}" method="post" style="display: inline;">
                          {% csrf_token %}
                          <button type="submit" class="d-none"></button>
                          <a href="#" class="badge bg-gradient-success text-decoration-none" onclick="event.preventDefault(); confirmAction('{{ profile.user.id }}', 'enable');">
                              Enable
                          </a>                        
                      </form>
                      {% endif %}
                  </td>
                  
                  <td class="align-middle text-center text-sm">
                      <span class="text-xs font-weight-bold">{{ profile.user.date_joined|date:"F d, Y" }}</span>
                  </td>
                  
                  <td class="align-middle text-center text-sm">
                      <div class="d-flex justify-content-center">
                          <a href="{% url 'edit_user' profile.user.id %}" class="text-secondary font-weight-bold text-sm me-2" data-toggle="tooltip" data-original-title="Edit user">
                              Edit
                          </a>
                          <form id="deleteUserForm{{ profile.user.id }}" action="{% url 'delete_user' profile.user.id %}" method="post">
                              {% csrf_token %}
                              <button type="submit" class="d-none"></button>
                              <a href="#" class="badge bg-gradient-danger text-decoration-none" onclick="confirmAction('{{ profile.user.id }}', 'delete');" data-toggle="tooltip" data-original-title="Delete user">Delete</a>
                          </form>
                      </div>
                  </td>
                </tr>
                {% endfor%}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
<!-- Include SweetAlert2 library -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function confirmAction(userId, action) {
        let title, text, confirmButtonText, formId;

        if (action === 'delete') {
            title = "Are you sure you want to delete?";
            text = "You won't be able to revert this!";
            confirmButtonText = "Yes, delete it!";
            formId = 'deleteUserForm';
        } else if (action === 'disable') {
            title = "Are you sure you want to disable?";
            text = "This user will no longer be able to perform actions.";
            confirmButtonText = "Yes, disable it!";
            formId = 'disableForm';
        } else if (action === 'enable') {
            title = "Are you sure you want to enable?";
            text = "This user will regain access to perform actions.";
            confirmButtonText = "Yes, enable it!";
            formId = 'enableForm';
        }

        Swal.fire({
            title: title,
            text: text,
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: confirmButtonText
        }).then((result) => {
            if (result.isConfirmed) {
                let successTitle, successText;
                if (action === 'delete') {
                    successTitle = "Deleted!";
                    successText = "The user has been deleted successfully.";
                } else if (action === 'disable') {
                    successTitle = "Disabled!";
                    successText = "The user has been disabled successfully.";
                } else if (action === 'enable') {
                    successTitle = "Enabled!";
                    successText = "The user has been enabled successfully.";
                }

                document.getElementById(formId + userId).submit();

                Swal.fire({
                    title: successTitle,
                    text: successText,
                    icon: "success",
                    timer: 3000,
                    timerProgressBar: true,
                    showConfirmButton: false 
                });
            }
        });
    }
</script>






{% endblock body %}